# Generated by Django 2.0.6 on 2018-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='album_logos/no-image.jpg', upload_to='images/imageRec.jpg')),
            ],
        ),
    ]
