# Generated by Django 2.0.6 on 2018-08-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='album_logos/no-image.jpg', upload_to='static/images'),
        ),
    ]
