# Generated by Django 2.0.6 on 2018-08-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180821_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='album_logos/no-image.jpg', upload_to='static/images'),
        ),
    ]
